version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - run:
          name: Needed deps
          command: apt-get update && apt-get install -y libfontconfig1
      - checkout
      - restore_cache:
          keys:
            - v1-net-dependencies-{{ checksum "CoreWms/CoreWms.csproj" }}
            - v1-net-dependencies-
      - run: dotnet test
      - save_cache:
          paths:
            - ~/.nuget/packages
          key: v1-net-dependencies-{{ checksum "CoreWms/CoreWms.csproj" }}

workflows:
  main:
    jobs:
      - test
