version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-net-dependencies-{{ checksum "src/net/FlatGeobuf/FlatGeobuf.csproj" }}
            - v1-net-dependencies-
      - run: dotnet test
      - save_cache:
          paths:
            - ~/.nuget/packages
          key: v1-net-dependencies-{{ checksum "src/net/FlatGeobuf/FlatGeobuf.csproj" }}

workflows:
  main:
    jobs:
      - test
